---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose: Provide a skeleton master playbook that imports individual
#          children playbooks that actually get the individual tasks done
#

#
# Variables that are defined in our variables.yaml file and
# referenced here are to be referenced using the {{ <var name> }}
# syntax.
#

################################################################
### Play 1: check if required variables are defined or not.
#           If not defined then simply exit the entire play
#
################################################################

- name: "Check if required variables that drive the deployment are defined"
  hosts: LocalMC   # this alias is specified in the inventory file
  remote_user:  "{{ local_user }}"  # since the play executes on LocalMC,
                                    # we use the local user
  gather_facts: no
  collections:    # collections is like import the necessary Ansible
                  # galaxy packages needed for the play to execute
  - ansible-base

  tasks:
  - import_tasks: tasks/playbook_check_variables.yaml


#####################################################
### Play 2: Create VMs on the Cloud
#
#####################################################
- name: "Play 2: Create VMs on Chameleon"
  hosts: LocalMC   # this alias is specified in the Inventory file
  remote_user:  "{{ local_user }}" 
  gather_facts: no 
  become: false    # No need for sudo as we are not installing anything
  collections:
  - ansible-base
  - openstack.cloud.collection
  
  tasks:    
  - import_tasks: tasks/playbook_create_vms.yaml

#####################################################
### Play 3: Get facts from Cloud VM
#
#####################################################
- name: "Play 3: Perform fact gathering on all Cloud VMs"
  hosts: LocalMC  # specified in the Inventory file
  remote_user:  "{{ local_user }}"
  gather_facts: no
  become: false
  collections:
  - ansible-base
  - openstack.cloud.collection

  tasks:    
  - import_tasks: tasks/playbook_retrieve_facts_vms.yaml

#####################################################
### Play 4: Install packages on our Cloud VMs
#
# Installing necessary packages for Kubernetes and Python
#####################################################
- name: "Play 4 - Install various packages on Cloud VMs"
  hosts: CloudVMs   # specified in the Inventory file
  remote_user: "{{ cloud_user }}" 
  become: true
  gather_facts: no
  collections:
  - ansible-base

  tasks:    
  - import_tasks: tasks/playbook_install_apt_packages.yaml
  - import_tasks: tasks/playbook_install_pip_packages.yaml

#####################################################
### Play 5: Install Docker and Kubernetes on Cloud VMs
#
# Installing Docker and Kubernetes packages
#####################################################
- name: "Play 5 - Install Docker and Kubernetes on Cloud VMs"
  hosts: CloudVMs   
  remote_user: "{{ cloud_user }}" 
  gather_facts: yes   
  become: true
  collections:
  - ansible-base

  tasks:    
  - import_tasks: tasks/playbook_install_docker.yaml
  - import_tasks: tasks/playbook_install_kubernetes.yaml

#####################################################
### Play 9: Set firewall rules for Kubernetes and Private Registry
#
#####################################################
- name: "Play 9 - Handle Firewall rules"
  hosts: CloudVMs   
  remote_user: "{{ cloud_user }}" 
  become: true
  gather_facts: no
  collections:
  - ansible-base
  - community.general

  tasks:    
  - import_tasks: tasks/playbook_set_firewalld_rules.yaml

#####################################################
### Play 6: Configure Private Docker Registry
#
#####################################################
- name: "Play 6 - Configure Private Docker Registry"
  hosts: [VM1]  
  remote_user: "{{ cloud_user }}" 
  become: true
  gather_facts: no
  collections:
  - ansible-base

  tasks:    
  - import_tasks: tasks/playbook_configure_docker_registry.yaml

#####################################################
### Play 7: Configure containerd for Kubernetes and Private Registry
#
#####################################################
- name: "Play 7 - Configure containerd for Kubernetes and Private Registry"
  hosts: CloudVMs   
  remote_user: "{{ cloud_user }}" 
  become: true
  gather_facts: no
  collections:
  - ansible-base

  tasks:    
  - import_tasks: tasks/playbook_configure_containerd.yaml

#####################################################
### Play 8: Restart containerd and Docker services
#
#####################################################
- name: "Play 8 - Restart containerd and Docker services"
  hosts: CloudVMs   
  remote_user: "{{ cloud_user }}" 
  become: true
  gather_facts: no
  collections:
  - ansible-base

  tasks:    
  - import_tasks: tasks/playbook_restart_services.yaml


#####################################################
### Play 10: Disable Swap on Cloud VMs
#
#####################################################
- name: "Play 10 - Disable Swap on Cloud VMs"
  hosts: CloudVMs   
  remote_user: "{{ cloud_user }}" 
  become: true
  gather_facts: no
  collections:
  - ansible-base

  tasks:    
  - import_tasks: tasks/playbook_disable_swap.yaml
