---
- name: "Update APT repositories"
  apt:
    update_cache: yes

- name: "Upgrade system packages"
  apt:
    upgrade: dist

- name: "Install necessary system packages"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - gnupg
      - python3
      - python3-pip
      - python3-dev
      - build-essential
      - default-jdk
      - git